# Generated by Django 2.1.3 on 2018-11-30 23:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import redeneural.event.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetup_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('long_description', models.TextField(verbose_name='Long Description')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Short Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('location', models.CharField(max_length=500, verbose_name='Location')),
                ('image', models.ImageField(blank=True, null=True, upload_to=redeneural.event.models.get_event_path, verbose_name='Image')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=redeneural.event.models.get_banner_path, verbose_name='Banner')),
                ('limit_participants', models.PositiveIntegerField(default=0, verbose_name='Limit Participants')),
                ('open_subscriptions_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Abrir inscrições em?')),
                ('close_subscriptions_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Encerrar inscrições em?')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active?')),
                ('meetup_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup_group.MeetupGroup')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
