# Generated by Django 2.1.3 on 2018-11-12 17:58

from django.db import migrations, models
import django_extensions.db.fields
import redeneural.event.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=['name'], unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('long_description', models.TextField(verbose_name='Long Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('location', models.CharField(max_length=500, verbose_name='Location')),
                ('image', models.ImageField(blank=True, null=True, upload_to=redeneural.event.models.get_event_path, verbose_name='Image')),
                ('limit_participants', models.PositiveIntegerField(default=0, verbose_name='Limit Participants')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active?')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
