# Generated by Django 2.1.3 on 2018-11-13 00:08

from django.db import migrations, models
import redeneural.event.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20181112_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=redeneural.event.models.get_banner_path, verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
