# Generated by Django 2.1.3 on 2018-11-13 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20181112_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='close_subscriptions_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Encerrar inscrições em?'),
        ),
        migrations.AddField(
            model_name='event',
            name='open_subscriptions_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Abrir inscrições em?'),
        ),
    ]
